title = "Alpaca LNA Drivers"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
can_reverse = true
step_size = 1.0
steps_per_sec = 6
com_port = 'COM12'
baudrate = 9600
can_find_home = true
can_park = false
can_set_alt = false
can_set_az = true
can_set_park = false
can_set_shutter = true
can_slave = true
can_sync = false

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
